name: Node.js Deploy To Tencent COS

on:
  push:
    barches:
      - master
  schedule:
  - cron:  '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    # 切代码到 runner
    - uses: actions/checkout@v1
      with:
        submodules: true
    # 使用 node:10
    - name: use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: npm install
      run: npm ci
    - name: npm run push
      run: npm run push
